// src/pages/App.vue
<script setup lang="ts">
import { ref, reactive } from 'vue';
let envValue = ref(process.env.NODE_ENV);
//console.log("page.App.env=", process.env.NODE_ENV)
//console.log("envValue=", envValue.value)
</script>

<template>
  <html>
    <head>
        <title>welcome</title>
        <span v-if="envValue === 'develop'"><link href="/static/main.css" rel="stylesheet" />
        </span>
        <span v-else><link href="/public/static/main.css" rel="stylesheet" />
        </span>
    </head>
    <body>
        <div id="app"></div>
        <span v-if="envValue === 'develop'"> <script type="module" src="/static/main.js"></script>
        </span>
        <span v-else><script type="module" src="/public/static/main.js"></script>
        </span>
    </body>
  </html>
</template>

<style scoped>
</style>
<!--
            {(process.env.NODE_ENV === "develop") ? (
                <script type="module" src="/static/main.js"></script>
            ): (
                <script type="module" src="/public/static/main.js"></script> 
            )}             

-->

// sample/user_auth/src/pages/App.tsx
import * as React from 'react';
//console.log("env=", process.env.NODE_ENV)
//
export default function Page() { 
    return (
    <html>
        <head>
            <title>welcome</title>
            {(process.env.NODE_ENV === "develop") ? (
                <link href="/static/style.css" rel="stylesheet" /> 
            ): (
                <link href="/public/static/style.css" rel="stylesheet" /> 
            )} 
        </head>
        <body>
            <div id="app"></div>
            {(process.env.NODE_ENV === "develop") ? (
                <script type="module" src="/static/main.js"></script>
            ): (
                <script type="module" src="/public/static/main.js"></script> 
            )}             
        </body>
    </html>
    );
}
/*
<div className="container mx-auto my-2 px-8 bg-white">
</div>
<a href="/">[ home ]</a>
<a href="/about">[ about ]</a>
<a href="/test">[ test ]</a>
<hr />
<h1 className="text-4xl font-bold">Hello!</h1>
*/
